#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
# shellcheck disable=SC1091
. "$SCRIPT_DIR/domain-policy.sh"

BASE_DOMAIN=${TUNNEL_BASE_DOMAIN:-}
ALLOWED_DOMAINS=${TUNNEL_ALLOWED_DOMAINS:-}
TARGET=${TUNNEL_NGINX_ALLOWLIST_FILE:-/etc/tunnel/portspan-allowed-hosts.conf}

validate_base_domain "$BASE_DOMAIN" || {
  echo "TUNNEL_BASE_DOMAIN must be a valid nested DNS name" >&2
  exit 1
}
validate_allowed_domains "$ALLOWED_DOMAINS" || {
  echo "TUNNEL_ALLOWED_DOMAINS must be unique lowercase labels separated by commas" >&2
  exit 1
}

SERVER_NAMES=$(allowed_domains_as_server_names "$ALLOWED_DOMAINS" "$BASE_DOMAIN")
TARGET_DIR=$(dirname "$TARGET")
install -d -m 755 "$TARGET_DIR"
TEMP_FILE=$(mktemp "$TARGET.tmp.XXXXXX")
cleanup() { rm -f "$TEMP_FILE"; }
trap cleanup EXIT INT TERM

{
  printf '# Generated by Portspan. Do not edit; update the allowlist inputs and rerun the renderer.\n'
  printf 'server_name %s;\n' "$SERVER_NAMES"
} > "$TEMP_FILE"

chmod 644 "$TEMP_FILE"
mv "$TEMP_FILE" "$TARGET"
trap - EXIT INT TERM
echo "Wrote Nginx host allowlist to $TARGET"
